application: zanaduu3
version: 002d
runtime: go
api_version: go1
automatic_scaling:
  min_idle_instances: 3
  max_pending_latency: 0.5s
instance_class: F2

skip_files:
# AppEngine defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Our additions
- node_modules

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon.ico
  secure: always

- url: /apple-touch-icon-precomposed.png
  static_files: static/images/arbital-icon-120.png
  upload: static/images/arbital-icon-120.png
  secure: always

- url: /apple-touch-icon.png
  static_files: static/images/arbital-icon-120.png
  upload: static/images/arbital-icon-120.png
  secure: always

- url: /.*
  script: _go_app
  secure: always

- url: /daemon
  script: _go_app
  login: admin
