application: zanaduu3
version: 001f
runtime: go
api_version: go1
automatic_scaling:
  min_idle_instances: 2
  max_pending_latency: 1s
instance_class: B1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: _go_app

- url: /daemon
  script: _go_app
  login: admin

