application: zanaduu3
version: 001e
runtime: go
api_version: go1
manual_scaling:
  instances: 1
instance_class: B1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: _go_app

- url: /daemon
  script: _go_app
  login: admin

